############# English navigation ##############

# main menu

[[main]]
name = "Home"
weight = 1
url = "/"

[[main]]
name = "Products"
weight = 2

[[main]]
name = "Prototypes"
weight = 3


[[main]]
name = "Contact"
url = "/contact/"
weight = 5


[[main]]
name = "About"
url = "/about/"
weight = 4

[[main]]
parent = "About"
name = "About Us"
url = "/about/"

[[main]]
parent = "About"
name = "Terms"
url = "/terms-conditions/"

[[main]]
parent = "About"
name = "Privacy"
url = "/privacy-policy/"

[[main]]
parent = "About"
name = "Imprint"
url = "/imprint/"






[[main]]
parent = "Prototypes"
name = "PsychDiary - AI Diary Mental Health Companion"
post = "AI-powered gratitude & mood diary with real-time insights and privacy-first design."
url = "/product/psychdiary/"
weight = 1

[[main]]
parent = "Prototypes"
name = "AI Assistant - Intelligent Email Assistant"
post = "Automatically sorts emails, blocks smart spam, and sends urgent alerts to Telegram or WhatsApp."
url = "/product/aiassistant/"
weight = 2

[[main]]
parent = "Prototypes"
name = "Decidify - Swipe-based Decision Assistant"
post = "Unify all messages and swipe through decisions with instant AI-generated replies."
url = "/product/decidify/"
weight = 3




[[main]]
parent = "Products"
name = "DocumentChat - RAG"
post = "Chat with Your Documents!"
url = "/liveproducts/documentchat/"





# footer menu

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3

[[footer]]
name = "Terms & Conditions"
url = "/terms-conditions"
weight = 4

# company menu
[[company]]
name = "About"
url = "/about/"

[[company]]
name = "Contact"
url = "/contact/"

[[services]]
name = "Contact"
url = "/contact/"
